<?php
/**
 * DocumentsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API de Facturación Electrónica SUNAT
 *
 * API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Intifact\Sdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Intifact\Sdk\ApiException;
use Intifact\Sdk\Configuration;
use Intifact\Sdk\FormDataProcessor;
use Intifact\Sdk\HeaderSelector;
use Intifact\Sdk\ObjectSerializer;

/**
 * DocumentsApi Class Doc Comment
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiV1CdrConsultarPost' => [
            'application/json',
        ],
        'apiV1DocumentsGet' => [
            'application/json',
        ],
        'apiV1DocumentsIdGet' => [
            'application/json',
        ],
        'apiV1DocumentsIdRecoverPost' => [
            'application/json',
        ],
        'apiV1DocumentsIdRetryPost' => [
            'application/json',
        ],
        'apiV1DocumentsNextCorrelativoGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV1CdrConsultarPost
     *
     * Consultar el CDR de un comprobante en SUNAT por referencia
     *
     * @param  \Intifact\Sdk\Model\ApiV1CdrConsultarPostRequest $api_v1_cdr_consultar_post_request api_v1_cdr_consultar_post_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1CdrConsultarPost'] to see the possible values for this operation
     *
     * @throws \Intifact\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Intifact\Sdk\Model\ApiV1CdrConsultarPost200Response|\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response|\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response
     */
    public function apiV1CdrConsultarPost($api_v1_cdr_consultar_post_request, string $contentType = self::contentTypes['apiV1CdrConsultarPost'][0])
    {
        list($response) = $this->apiV1CdrConsultarPostWithHttpInfo($api_v1_cdr_consultar_post_request, $contentType);
        return $response;
    }

    /**
     * Operation apiV1CdrConsultarPostWithHttpInfo
     *
     * Consultar el CDR de un comprobante en SUNAT por referencia
     *
     * @param  \Intifact\Sdk\Model\ApiV1CdrConsultarPostRequest $api_v1_cdr_consultar_post_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1CdrConsultarPost'] to see the possible values for this operation
     *
     * @throws \Intifact\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Intifact\Sdk\Model\ApiV1CdrConsultarPost200Response|\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response|\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1CdrConsultarPostWithHttpInfo($api_v1_cdr_consultar_post_request, string $contentType = self::contentTypes['apiV1CdrConsultarPost'][0])
    {
        $request = $this->apiV1CdrConsultarPostRequest($api_v1_cdr_consultar_post_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Intifact\Sdk\Model\ApiV1CdrConsultarPost200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Intifact\Sdk\Model\ApiV1CdrConsultarPost200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Intifact\Sdk\Model\ApiV1CdrConsultarPost200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1CdrConsultarPostAsync
     *
     * Consultar el CDR de un comprobante en SUNAT por referencia
     *
     * @param  \Intifact\Sdk\Model\ApiV1CdrConsultarPostRequest $api_v1_cdr_consultar_post_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1CdrConsultarPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1CdrConsultarPostAsync($api_v1_cdr_consultar_post_request, string $contentType = self::contentTypes['apiV1CdrConsultarPost'][0])
    {
        return $this->apiV1CdrConsultarPostAsyncWithHttpInfo($api_v1_cdr_consultar_post_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1CdrConsultarPostAsyncWithHttpInfo
     *
     * Consultar el CDR de un comprobante en SUNAT por referencia
     *
     * @param  \Intifact\Sdk\Model\ApiV1CdrConsultarPostRequest $api_v1_cdr_consultar_post_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1CdrConsultarPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1CdrConsultarPostAsyncWithHttpInfo($api_v1_cdr_consultar_post_request, string $contentType = self::contentTypes['apiV1CdrConsultarPost'][0])
    {
        $returnType = '\Intifact\Sdk\Model\ApiV1CdrConsultarPost200Response';
        $request = $this->apiV1CdrConsultarPostRequest($api_v1_cdr_consultar_post_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1CdrConsultarPost'
     *
     * @param  \Intifact\Sdk\Model\ApiV1CdrConsultarPostRequest $api_v1_cdr_consultar_post_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1CdrConsultarPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1CdrConsultarPostRequest($api_v1_cdr_consultar_post_request, string $contentType = self::contentTypes['apiV1CdrConsultarPost'][0])
    {

        // verify the required parameter 'api_v1_cdr_consultar_post_request' is set
        if ($api_v1_cdr_consultar_post_request === null || (is_array($api_v1_cdr_consultar_post_request) && count($api_v1_cdr_consultar_post_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_v1_cdr_consultar_post_request when calling apiV1CdrConsultarPost'
            );
        }


        $resourcePath = '/api/v1/cdr/consultar';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($api_v1_cdr_consultar_post_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($api_v1_cdr_consultar_post_request), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $api_v1_cdr_consultar_post_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1DocumentsGet
     *
     * Listar documentos con filtros y paginación
     *
     * @param  string|null $ruc ruc (optional)
     * @param  string|null $tipo_doc tipo_doc (optional)
     * @param  string|null $serie serie (optional)
     * @param  string|null $estado estado (optional)
     * @param  string|null $env env (optional)
     * @param  string|null $fecha_desde fecha_desde (optional)
     * @param  string|null $fecha_hasta fecha_hasta (optional)
     * @param  string|null $cliente_num_doc cliente_num_doc (optional)
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $limit limit (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsGet'] to see the possible values for this operation
     *
     * @throws \Intifact\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Intifact\Sdk\Model\ApiV1DocumentsGet200Response
     */
    public function apiV1DocumentsGet($ruc = null, $tipo_doc = null, $serie = null, $estado = null, $env = null, $fecha_desde = null, $fecha_hasta = null, $cliente_num_doc = null, $page = 1, $limit = 20, string $contentType = self::contentTypes['apiV1DocumentsGet'][0])
    {
        list($response) = $this->apiV1DocumentsGetWithHttpInfo($ruc, $tipo_doc, $serie, $estado, $env, $fecha_desde, $fecha_hasta, $cliente_num_doc, $page, $limit, $contentType);
        return $response;
    }

    /**
     * Operation apiV1DocumentsGetWithHttpInfo
     *
     * Listar documentos con filtros y paginación
     *
     * @param  string|null $ruc (optional)
     * @param  string|null $tipo_doc (optional)
     * @param  string|null $serie (optional)
     * @param  string|null $estado (optional)
     * @param  string|null $env (optional)
     * @param  string|null $fecha_desde (optional)
     * @param  string|null $fecha_hasta (optional)
     * @param  string|null $cliente_num_doc (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsGet'] to see the possible values for this operation
     *
     * @throws \Intifact\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Intifact\Sdk\Model\ApiV1DocumentsGet200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1DocumentsGetWithHttpInfo($ruc = null, $tipo_doc = null, $serie = null, $estado = null, $env = null, $fecha_desde = null, $fecha_hasta = null, $cliente_num_doc = null, $page = 1, $limit = 20, string $contentType = self::contentTypes['apiV1DocumentsGet'][0])
    {
        $request = $this->apiV1DocumentsGetRequest($ruc, $tipo_doc, $serie, $estado, $env, $fecha_desde, $fecha_hasta, $cliente_num_doc, $page, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Intifact\Sdk\Model\ApiV1DocumentsGet200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Intifact\Sdk\Model\ApiV1DocumentsGet200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Intifact\Sdk\Model\ApiV1DocumentsGet200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1DocumentsGetAsync
     *
     * Listar documentos con filtros y paginación
     *
     * @param  string|null $ruc (optional)
     * @param  string|null $tipo_doc (optional)
     * @param  string|null $serie (optional)
     * @param  string|null $estado (optional)
     * @param  string|null $env (optional)
     * @param  string|null $fecha_desde (optional)
     * @param  string|null $fecha_hasta (optional)
     * @param  string|null $cliente_num_doc (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1DocumentsGetAsync($ruc = null, $tipo_doc = null, $serie = null, $estado = null, $env = null, $fecha_desde = null, $fecha_hasta = null, $cliente_num_doc = null, $page = 1, $limit = 20, string $contentType = self::contentTypes['apiV1DocumentsGet'][0])
    {
        return $this->apiV1DocumentsGetAsyncWithHttpInfo($ruc, $tipo_doc, $serie, $estado, $env, $fecha_desde, $fecha_hasta, $cliente_num_doc, $page, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1DocumentsGetAsyncWithHttpInfo
     *
     * Listar documentos con filtros y paginación
     *
     * @param  string|null $ruc (optional)
     * @param  string|null $tipo_doc (optional)
     * @param  string|null $serie (optional)
     * @param  string|null $estado (optional)
     * @param  string|null $env (optional)
     * @param  string|null $fecha_desde (optional)
     * @param  string|null $fecha_hasta (optional)
     * @param  string|null $cliente_num_doc (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1DocumentsGetAsyncWithHttpInfo($ruc = null, $tipo_doc = null, $serie = null, $estado = null, $env = null, $fecha_desde = null, $fecha_hasta = null, $cliente_num_doc = null, $page = 1, $limit = 20, string $contentType = self::contentTypes['apiV1DocumentsGet'][0])
    {
        $returnType = '\Intifact\Sdk\Model\ApiV1DocumentsGet200Response';
        $request = $this->apiV1DocumentsGetRequest($ruc, $tipo_doc, $serie, $estado, $env, $fecha_desde, $fecha_hasta, $cliente_num_doc, $page, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1DocumentsGet'
     *
     * @param  string|null $ruc (optional)
     * @param  string|null $tipo_doc (optional)
     * @param  string|null $serie (optional)
     * @param  string|null $estado (optional)
     * @param  string|null $env (optional)
     * @param  string|null $fecha_desde (optional)
     * @param  string|null $fecha_hasta (optional)
     * @param  string|null $cliente_num_doc (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1DocumentsGetRequest($ruc = null, $tipo_doc = null, $serie = null, $estado = null, $env = null, $fecha_desde = null, $fecha_hasta = null, $cliente_num_doc = null, $page = 1, $limit = 20, string $contentType = self::contentTypes['apiV1DocumentsGet'][0])
    {

        if ($ruc !== null && strlen($ruc) > 11) {
            throw new \InvalidArgumentException('invalid length for "$ruc" when calling DocumentsApi.apiV1DocumentsGet, must be smaller than or equal to 11.');
        }
        if ($ruc !== null && strlen($ruc) < 11) {
            throw new \InvalidArgumentException('invalid length for "$ruc" when calling DocumentsApi.apiV1DocumentsGet, must be bigger than or equal to 11.');
        }
        







        if ($page !== null && $page > 9007199254740991) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling DocumentsApi.apiV1DocumentsGet, must be smaller than or equal to 9007199254740991.');
        }
        if ($page !== null && $page <= 0) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling DocumentsApi.apiV1DocumentsGet, must be bigger than 0.');
        }
        
        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling DocumentsApi.apiV1DocumentsGet, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling DocumentsApi.apiV1DocumentsGet, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/api/v1/documents';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ruc,
            'ruc', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tipo_doc,
            'tipoDoc', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $serie,
            'serie', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $estado,
            'estado', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $env,
            'env', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fecha_desde,
            'fechaDesde', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fecha_hasta,
            'fechaHasta', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cliente_num_doc,
            'clienteNumDoc', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1DocumentsIdGet
     *
     * Detalle completo de un documento
     *
     * @param  string $id id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdGet'] to see the possible values for this operation
     *
     * @throws \Intifact\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1DocumentsIdGet($id, string $contentType = self::contentTypes['apiV1DocumentsIdGet'][0])
    {
        $this->apiV1DocumentsIdGetWithHttpInfo($id, $contentType);
    }

    /**
     * Operation apiV1DocumentsIdGetWithHttpInfo
     *
     * Detalle completo de un documento
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdGet'] to see the possible values for this operation
     *
     * @throws \Intifact\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1DocumentsIdGetWithHttpInfo($id, string $contentType = self::contentTypes['apiV1DocumentsIdGet'][0])
    {
        $request = $this->apiV1DocumentsIdGetRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1DocumentsIdGetAsync
     *
     * Detalle completo de un documento
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1DocumentsIdGetAsync($id, string $contentType = self::contentTypes['apiV1DocumentsIdGet'][0])
    {
        return $this->apiV1DocumentsIdGetAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1DocumentsIdGetAsyncWithHttpInfo
     *
     * Detalle completo de un documento
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1DocumentsIdGetAsyncWithHttpInfo($id, string $contentType = self::contentTypes['apiV1DocumentsIdGet'][0])
    {
        $returnType = '';
        $request = $this->apiV1DocumentsIdGetRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1DocumentsIdGet'
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1DocumentsIdGetRequest($id, string $contentType = self::contentTypes['apiV1DocumentsIdGet'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling apiV1DocumentsIdGet'
            );
        }
        if (!preg_match("/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/", $id)) {
            throw new \InvalidArgumentException("invalid value for \"id\" when calling DocumentsApi.apiV1DocumentsIdGet, must conform to the pattern /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/.");
        }
        

        $resourcePath = '/api/v1/documents/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1DocumentsIdRecoverPost
     *
     * Reconciliar un documento con SUNAT (consulta de CDR, solo master)
     *
     * @param  string $id id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdRecoverPost'] to see the possible values for this operation
     *
     * @throws \Intifact\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Intifact\Sdk\Model\ApiV1DocumentsIdRecoverPost200Response|\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response|\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response|\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response
     */
    public function apiV1DocumentsIdRecoverPost($id, string $contentType = self::contentTypes['apiV1DocumentsIdRecoverPost'][0])
    {
        list($response) = $this->apiV1DocumentsIdRecoverPostWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation apiV1DocumentsIdRecoverPostWithHttpInfo
     *
     * Reconciliar un documento con SUNAT (consulta de CDR, solo master)
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdRecoverPost'] to see the possible values for this operation
     *
     * @throws \Intifact\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Intifact\Sdk\Model\ApiV1DocumentsIdRecoverPost200Response|\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response|\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response|\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1DocumentsIdRecoverPostWithHttpInfo($id, string $contentType = self::contentTypes['apiV1DocumentsIdRecoverPost'][0])
    {
        $request = $this->apiV1DocumentsIdRecoverPostRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Intifact\Sdk\Model\ApiV1DocumentsIdRecoverPost200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Intifact\Sdk\Model\ApiV1DocumentsIdRecoverPost200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Intifact\Sdk\Model\ApiV1DocumentsIdRecoverPost200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1DocumentsIdRecoverPostAsync
     *
     * Reconciliar un documento con SUNAT (consulta de CDR, solo master)
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdRecoverPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1DocumentsIdRecoverPostAsync($id, string $contentType = self::contentTypes['apiV1DocumentsIdRecoverPost'][0])
    {
        return $this->apiV1DocumentsIdRecoverPostAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1DocumentsIdRecoverPostAsyncWithHttpInfo
     *
     * Reconciliar un documento con SUNAT (consulta de CDR, solo master)
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdRecoverPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1DocumentsIdRecoverPostAsyncWithHttpInfo($id, string $contentType = self::contentTypes['apiV1DocumentsIdRecoverPost'][0])
    {
        $returnType = '\Intifact\Sdk\Model\ApiV1DocumentsIdRecoverPost200Response';
        $request = $this->apiV1DocumentsIdRecoverPostRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1DocumentsIdRecoverPost'
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdRecoverPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1DocumentsIdRecoverPostRequest($id, string $contentType = self::contentTypes['apiV1DocumentsIdRecoverPost'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling apiV1DocumentsIdRecoverPost'
            );
        }
        if (!preg_match("/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/", $id)) {
            throw new \InvalidArgumentException("invalid value for \"id\" when calling DocumentsApi.apiV1DocumentsIdRecoverPost, must conform to the pattern /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/.");
        }
        

        $resourcePath = '/api/v1/documents/{id}/recover';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1DocumentsIdRetryPost
     *
     * Re-encolar un documento fallido
     *
     * @param  string $id id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdRetryPost'] to see the possible values for this operation
     *
     * @throws \Intifact\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Intifact\Sdk\Model\ApiV1DocumentsIdRetryPost202Response|\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response
     */
    public function apiV1DocumentsIdRetryPost($id, string $contentType = self::contentTypes['apiV1DocumentsIdRetryPost'][0])
    {
        list($response) = $this->apiV1DocumentsIdRetryPostWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation apiV1DocumentsIdRetryPostWithHttpInfo
     *
     * Re-encolar un documento fallido
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdRetryPost'] to see the possible values for this operation
     *
     * @throws \Intifact\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Intifact\Sdk\Model\ApiV1DocumentsIdRetryPost202Response|\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1DocumentsIdRetryPostWithHttpInfo($id, string $contentType = self::contentTypes['apiV1DocumentsIdRetryPost'][0])
    {
        $request = $this->apiV1DocumentsIdRetryPostRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 202:
                    return $this->handleResponseWithDataType(
                        '\Intifact\Sdk\Model\ApiV1DocumentsIdRetryPost202Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Intifact\Sdk\Model\ApiV1DocumentsIdRetryPost202Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Intifact\Sdk\Model\ApiV1DocumentsIdRetryPost202Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1DocumentsIdRetryPostAsync
     *
     * Re-encolar un documento fallido
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdRetryPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1DocumentsIdRetryPostAsync($id, string $contentType = self::contentTypes['apiV1DocumentsIdRetryPost'][0])
    {
        return $this->apiV1DocumentsIdRetryPostAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1DocumentsIdRetryPostAsyncWithHttpInfo
     *
     * Re-encolar un documento fallido
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdRetryPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1DocumentsIdRetryPostAsyncWithHttpInfo($id, string $contentType = self::contentTypes['apiV1DocumentsIdRetryPost'][0])
    {
        $returnType = '\Intifact\Sdk\Model\ApiV1DocumentsIdRetryPost202Response';
        $request = $this->apiV1DocumentsIdRetryPostRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1DocumentsIdRetryPost'
     *
     * @param  string $id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsIdRetryPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1DocumentsIdRetryPostRequest($id, string $contentType = self::contentTypes['apiV1DocumentsIdRetryPost'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling apiV1DocumentsIdRetryPost'
            );
        }
        if (!preg_match("/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/", $id)) {
            throw new \InvalidArgumentException("invalid value for \"id\" when calling DocumentsApi.apiV1DocumentsIdRetryPost, must conform to the pattern /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/.");
        }
        

        $resourcePath = '/api/v1/documents/{id}/retry';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1DocumentsNextCorrelativoGet
     *
     * Obtener el siguiente correlativo disponible para una serie
     *
     * @param  string $company_ruc company_ruc (required)
     * @param  string $tipo_doc tipo_doc (required)
     * @param  string $serie serie (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsNextCorrelativoGet'] to see the possible values for this operation
     *
     * @throws \Intifact\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Intifact\Sdk\Model\ApiV1DocumentsNextCorrelativoGet200Response|\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response
     */
    public function apiV1DocumentsNextCorrelativoGet($company_ruc, $tipo_doc, $serie, string $contentType = self::contentTypes['apiV1DocumentsNextCorrelativoGet'][0])
    {
        list($response) = $this->apiV1DocumentsNextCorrelativoGetWithHttpInfo($company_ruc, $tipo_doc, $serie, $contentType);
        return $response;
    }

    /**
     * Operation apiV1DocumentsNextCorrelativoGetWithHttpInfo
     *
     * Obtener el siguiente correlativo disponible para una serie
     *
     * @param  string $company_ruc (required)
     * @param  string $tipo_doc (required)
     * @param  string $serie (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsNextCorrelativoGet'] to see the possible values for this operation
     *
     * @throws \Intifact\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Intifact\Sdk\Model\ApiV1DocumentsNextCorrelativoGet200Response|\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1DocumentsNextCorrelativoGetWithHttpInfo($company_ruc, $tipo_doc, $serie, string $contentType = self::contentTypes['apiV1DocumentsNextCorrelativoGet'][0])
    {
        $request = $this->apiV1DocumentsNextCorrelativoGetRequest($company_ruc, $tipo_doc, $serie, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Intifact\Sdk\Model\ApiV1DocumentsNextCorrelativoGet200Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Intifact\Sdk\Model\ApiV1DocumentsNextCorrelativoGet200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Intifact\Sdk\Model\ApiV1DocumentsNextCorrelativoGet200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Intifact\Sdk\Model\ApiV1InvoiceSendPost400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1DocumentsNextCorrelativoGetAsync
     *
     * Obtener el siguiente correlativo disponible para una serie
     *
     * @param  string $company_ruc (required)
     * @param  string $tipo_doc (required)
     * @param  string $serie (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsNextCorrelativoGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1DocumentsNextCorrelativoGetAsync($company_ruc, $tipo_doc, $serie, string $contentType = self::contentTypes['apiV1DocumentsNextCorrelativoGet'][0])
    {
        return $this->apiV1DocumentsNextCorrelativoGetAsyncWithHttpInfo($company_ruc, $tipo_doc, $serie, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1DocumentsNextCorrelativoGetAsyncWithHttpInfo
     *
     * Obtener el siguiente correlativo disponible para una serie
     *
     * @param  string $company_ruc (required)
     * @param  string $tipo_doc (required)
     * @param  string $serie (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsNextCorrelativoGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1DocumentsNextCorrelativoGetAsyncWithHttpInfo($company_ruc, $tipo_doc, $serie, string $contentType = self::contentTypes['apiV1DocumentsNextCorrelativoGet'][0])
    {
        $returnType = '\Intifact\Sdk\Model\ApiV1DocumentsNextCorrelativoGet200Response';
        $request = $this->apiV1DocumentsNextCorrelativoGetRequest($company_ruc, $tipo_doc, $serie, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1DocumentsNextCorrelativoGet'
     *
     * @param  string $company_ruc (required)
     * @param  string $tipo_doc (required)
     * @param  string $serie (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1DocumentsNextCorrelativoGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1DocumentsNextCorrelativoGetRequest($company_ruc, $tipo_doc, $serie, string $contentType = self::contentTypes['apiV1DocumentsNextCorrelativoGet'][0])
    {

        // verify the required parameter 'company_ruc' is set
        if ($company_ruc === null || (is_array($company_ruc) && count($company_ruc) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_ruc when calling apiV1DocumentsNextCorrelativoGet'
            );
        }
        if (strlen($company_ruc) > 11) {
            throw new \InvalidArgumentException('invalid length for "$company_ruc" when calling DocumentsApi.apiV1DocumentsNextCorrelativoGet, must be smaller than or equal to 11.');
        }
        if (strlen($company_ruc) < 11) {
            throw new \InvalidArgumentException('invalid length for "$company_ruc" when calling DocumentsApi.apiV1DocumentsNextCorrelativoGet, must be bigger than or equal to 11.');
        }
        
        // verify the required parameter 'tipo_doc' is set
        if ($tipo_doc === null || (is_array($tipo_doc) && count($tipo_doc) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tipo_doc when calling apiV1DocumentsNextCorrelativoGet'
            );
        }
        if (strlen($tipo_doc) > 2) {
            throw new \InvalidArgumentException('invalid length for "$tipo_doc" when calling DocumentsApi.apiV1DocumentsNextCorrelativoGet, must be smaller than or equal to 2.');
        }
        if (strlen($tipo_doc) < 1) {
            throw new \InvalidArgumentException('invalid length for "$tipo_doc" when calling DocumentsApi.apiV1DocumentsNextCorrelativoGet, must be bigger than or equal to 1.');
        }
        
        // verify the required parameter 'serie' is set
        if ($serie === null || (is_array($serie) && count($serie) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $serie when calling apiV1DocumentsNextCorrelativoGet'
            );
        }
        if (strlen($serie) > 4) {
            throw new \InvalidArgumentException('invalid length for "$serie" when calling DocumentsApi.apiV1DocumentsNextCorrelativoGet, must be smaller than or equal to 4.');
        }
        if (strlen($serie) < 4) {
            throw new \InvalidArgumentException('invalid length for "$serie" when calling DocumentsApi.apiV1DocumentsNextCorrelativoGet, must be bigger than or equal to 4.');
        }
        

        $resourcePath = '/api/v1/documents/next-correlativo';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $company_ruc,
            'companyRuc', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tipo_doc,
            'tipoDoc', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $serie,
            'serie', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
