<?php
/**
 * ApiV1QueuesStatsGet200ResponseData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API de Facturación Electrónica SUNAT
 *
 * API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Intifact\Sdk\Model;

use \ArrayAccess;
use \Intifact\Sdk\ObjectSerializer;

/**
 * ApiV1QueuesStatsGet200ResponseData Class Doc Comment
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApiV1QueuesStatsGet200ResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = '_api_v1_queues_stats_get_200_response_data';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'sunat_send' => 'array<string,float>',
        'sunat_summary' => 'array<string,float>',
        'sunat_ticket_poll' => 'array<string,float>',
        'sunat_gre_send' => 'array<string,float>',
        'sunat_gre_ticket_poll' => 'array<string,float>'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'sunat_send' => null,
        'sunat_summary' => null,
        'sunat_ticket_poll' => null,
        'sunat_gre_send' => null,
        'sunat_gre_ticket_poll' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'sunat_send' => false,
        'sunat_summary' => false,
        'sunat_ticket_poll' => false,
        'sunat_gre_send' => false,
        'sunat_gre_ticket_poll' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sunat_send' => 'sunat-send',
        'sunat_summary' => 'sunat-summary',
        'sunat_ticket_poll' => 'sunat-ticket-poll',
        'sunat_gre_send' => 'sunat-gre-send',
        'sunat_gre_ticket_poll' => 'sunat-gre-ticket-poll'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sunat_send' => 'setSunatSend',
        'sunat_summary' => 'setSunatSummary',
        'sunat_ticket_poll' => 'setSunatTicketPoll',
        'sunat_gre_send' => 'setSunatGreSend',
        'sunat_gre_ticket_poll' => 'setSunatGreTicketPoll'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sunat_send' => 'getSunatSend',
        'sunat_summary' => 'getSunatSummary',
        'sunat_ticket_poll' => 'getSunatTicketPoll',
        'sunat_gre_send' => 'getSunatGreSend',
        'sunat_gre_ticket_poll' => 'getSunatGreTicketPoll'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('sunat_send', $data ?? [], null);
        $this->setIfExists('sunat_summary', $data ?? [], null);
        $this->setIfExists('sunat_ticket_poll', $data ?? [], null);
        $this->setIfExists('sunat_gre_send', $data ?? [], null);
        $this->setIfExists('sunat_gre_ticket_poll', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['sunat_send'] === null) {
            $invalidProperties[] = "'sunat_send' can't be null";
        }
        if ($this->container['sunat_summary'] === null) {
            $invalidProperties[] = "'sunat_summary' can't be null";
        }
        if ($this->container['sunat_ticket_poll'] === null) {
            $invalidProperties[] = "'sunat_ticket_poll' can't be null";
        }
        if ($this->container['sunat_gre_send'] === null) {
            $invalidProperties[] = "'sunat_gre_send' can't be null";
        }
        if ($this->container['sunat_gre_ticket_poll'] === null) {
            $invalidProperties[] = "'sunat_gre_ticket_poll' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sunat_send
     *
     * @return array<string,float>
     */
    public function getSunatSend()
    {
        return $this->container['sunat_send'];
    }

    /**
     * Sets sunat_send
     *
     * @param array<string,float> $sunat_send sunat_send
     *
     * @return self
     */
    public function setSunatSend($sunat_send)
    {
        if (is_null($sunat_send)) {
            throw new \InvalidArgumentException('non-nullable sunat_send cannot be null');
        }
        $this->container['sunat_send'] = $sunat_send;

        return $this;
    }

    /**
     * Gets sunat_summary
     *
     * @return array<string,float>
     */
    public function getSunatSummary()
    {
        return $this->container['sunat_summary'];
    }

    /**
     * Sets sunat_summary
     *
     * @param array<string,float> $sunat_summary sunat_summary
     *
     * @return self
     */
    public function setSunatSummary($sunat_summary)
    {
        if (is_null($sunat_summary)) {
            throw new \InvalidArgumentException('non-nullable sunat_summary cannot be null');
        }
        $this->container['sunat_summary'] = $sunat_summary;

        return $this;
    }

    /**
     * Gets sunat_ticket_poll
     *
     * @return array<string,float>
     */
    public function getSunatTicketPoll()
    {
        return $this->container['sunat_ticket_poll'];
    }

    /**
     * Sets sunat_ticket_poll
     *
     * @param array<string,float> $sunat_ticket_poll sunat_ticket_poll
     *
     * @return self
     */
    public function setSunatTicketPoll($sunat_ticket_poll)
    {
        if (is_null($sunat_ticket_poll)) {
            throw new \InvalidArgumentException('non-nullable sunat_ticket_poll cannot be null');
        }
        $this->container['sunat_ticket_poll'] = $sunat_ticket_poll;

        return $this;
    }

    /**
     * Gets sunat_gre_send
     *
     * @return array<string,float>
     */
    public function getSunatGreSend()
    {
        return $this->container['sunat_gre_send'];
    }

    /**
     * Sets sunat_gre_send
     *
     * @param array<string,float> $sunat_gre_send sunat_gre_send
     *
     * @return self
     */
    public function setSunatGreSend($sunat_gre_send)
    {
        if (is_null($sunat_gre_send)) {
            throw new \InvalidArgumentException('non-nullable sunat_gre_send cannot be null');
        }
        $this->container['sunat_gre_send'] = $sunat_gre_send;

        return $this;
    }

    /**
     * Gets sunat_gre_ticket_poll
     *
     * @return array<string,float>
     */
    public function getSunatGreTicketPoll()
    {
        return $this->container['sunat_gre_ticket_poll'];
    }

    /**
     * Sets sunat_gre_ticket_poll
     *
     * @param array<string,float> $sunat_gre_ticket_poll sunat_gre_ticket_poll
     *
     * @return self
     */
    public function setSunatGreTicketPoll($sunat_gre_ticket_poll)
    {
        if (is_null($sunat_gre_ticket_poll)) {
            throw new \InvalidArgumentException('non-nullable sunat_gre_ticket_poll cannot be null');
        }
        $this->container['sunat_gre_ticket_poll'] = $sunat_gre_ticket_poll;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


