<?php
/**
 * ApiV1CompaniesIdPutRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API de Facturación Electrónica SUNAT
 *
 * API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Intifact\Sdk\Model;

use \ArrayAccess;
use \Intifact\Sdk\ObjectSerializer;

/**
 * ApiV1CompaniesIdPutRequest Class Doc Comment
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApiV1CompaniesIdPutRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = '_api_v1_companies__id__put_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'ruc' => 'string',
        'razon_social' => 'string',
        'nombre_comercial' => 'string',
        'ubigeo' => 'string',
        'direccion' => 'string',
        'departamento' => 'string',
        'provincia' => 'string',
        'distrito' => 'string',
        'urbanizacion' => 'string',
        'telefono' => 'string',
        'email' => 'string',
        'web' => 'string',
        'sol_user' => 'string',
        'sol_password' => 'string',
        'tenant_id' => 'string',
        'gre_client_id' => 'string',
        'gre_client_secret' => 'string',
        'sunat_production' => 'bool',
        'cuentas_bancarias' => '\Intifact\Sdk\Model\ApiV1CompaniesPostRequestCuentasBancariasInner[]',
        'terminos_titulo' => 'string',
        'terminos' => 'string[]',
        'nota_pago_titulo' => 'string',
        'nota_pago_texto' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'ruc' => null,
        'razon_social' => null,
        'nombre_comercial' => null,
        'ubigeo' => null,
        'direccion' => null,
        'departamento' => null,
        'provincia' => null,
        'distrito' => null,
        'urbanizacion' => null,
        'telefono' => null,
        'email' => 'email',
        'web' => null,
        'sol_user' => null,
        'sol_password' => null,
        'tenant_id' => 'uuid',
        'gre_client_id' => null,
        'gre_client_secret' => null,
        'sunat_production' => null,
        'cuentas_bancarias' => null,
        'terminos_titulo' => null,
        'terminos' => null,
        'nota_pago_titulo' => null,
        'nota_pago_texto' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'ruc' => false,
        'razon_social' => false,
        'nombre_comercial' => false,
        'ubigeo' => false,
        'direccion' => false,
        'departamento' => false,
        'provincia' => false,
        'distrito' => false,
        'urbanizacion' => false,
        'telefono' => false,
        'email' => false,
        'web' => true,
        'sol_user' => false,
        'sol_password' => false,
        'tenant_id' => false,
        'gre_client_id' => false,
        'gre_client_secret' => false,
        'sunat_production' => false,
        'cuentas_bancarias' => false,
        'terminos_titulo' => true,
        'terminos' => false,
        'nota_pago_titulo' => true,
        'nota_pago_texto' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ruc' => 'ruc',
        'razon_social' => 'razonSocial',
        'nombre_comercial' => 'nombreComercial',
        'ubigeo' => 'ubigeo',
        'direccion' => 'direccion',
        'departamento' => 'departamento',
        'provincia' => 'provincia',
        'distrito' => 'distrito',
        'urbanizacion' => 'urbanizacion',
        'telefono' => 'telefono',
        'email' => 'email',
        'web' => 'web',
        'sol_user' => 'solUser',
        'sol_password' => 'solPassword',
        'tenant_id' => 'tenantId',
        'gre_client_id' => 'greClientId',
        'gre_client_secret' => 'greClientSecret',
        'sunat_production' => 'sunatProduction',
        'cuentas_bancarias' => 'cuentasBancarias',
        'terminos_titulo' => 'terminosTitulo',
        'terminos' => 'terminos',
        'nota_pago_titulo' => 'notaPagoTitulo',
        'nota_pago_texto' => 'notaPagoTexto'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ruc' => 'setRuc',
        'razon_social' => 'setRazonSocial',
        'nombre_comercial' => 'setNombreComercial',
        'ubigeo' => 'setUbigeo',
        'direccion' => 'setDireccion',
        'departamento' => 'setDepartamento',
        'provincia' => 'setProvincia',
        'distrito' => 'setDistrito',
        'urbanizacion' => 'setUrbanizacion',
        'telefono' => 'setTelefono',
        'email' => 'setEmail',
        'web' => 'setWeb',
        'sol_user' => 'setSolUser',
        'sol_password' => 'setSolPassword',
        'tenant_id' => 'setTenantId',
        'gre_client_id' => 'setGreClientId',
        'gre_client_secret' => 'setGreClientSecret',
        'sunat_production' => 'setSunatProduction',
        'cuentas_bancarias' => 'setCuentasBancarias',
        'terminos_titulo' => 'setTerminosTitulo',
        'terminos' => 'setTerminos',
        'nota_pago_titulo' => 'setNotaPagoTitulo',
        'nota_pago_texto' => 'setNotaPagoTexto'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ruc' => 'getRuc',
        'razon_social' => 'getRazonSocial',
        'nombre_comercial' => 'getNombreComercial',
        'ubigeo' => 'getUbigeo',
        'direccion' => 'getDireccion',
        'departamento' => 'getDepartamento',
        'provincia' => 'getProvincia',
        'distrito' => 'getDistrito',
        'urbanizacion' => 'getUrbanizacion',
        'telefono' => 'getTelefono',
        'email' => 'getEmail',
        'web' => 'getWeb',
        'sol_user' => 'getSolUser',
        'sol_password' => 'getSolPassword',
        'tenant_id' => 'getTenantId',
        'gre_client_id' => 'getGreClientId',
        'gre_client_secret' => 'getGreClientSecret',
        'sunat_production' => 'getSunatProduction',
        'cuentas_bancarias' => 'getCuentasBancarias',
        'terminos_titulo' => 'getTerminosTitulo',
        'terminos' => 'getTerminos',
        'nota_pago_titulo' => 'getNotaPagoTitulo',
        'nota_pago_texto' => 'getNotaPagoTexto'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('ruc', $data ?? [], null);
        $this->setIfExists('razon_social', $data ?? [], null);
        $this->setIfExists('nombre_comercial', $data ?? [], null);
        $this->setIfExists('ubigeo', $data ?? [], null);
        $this->setIfExists('direccion', $data ?? [], null);
        $this->setIfExists('departamento', $data ?? [], null);
        $this->setIfExists('provincia', $data ?? [], null);
        $this->setIfExists('distrito', $data ?? [], null);
        $this->setIfExists('urbanizacion', $data ?? [], null);
        $this->setIfExists('telefono', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('web', $data ?? [], null);
        $this->setIfExists('sol_user', $data ?? [], null);
        $this->setIfExists('sol_password', $data ?? [], null);
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('gre_client_id', $data ?? [], null);
        $this->setIfExists('gre_client_secret', $data ?? [], null);
        $this->setIfExists('sunat_production', $data ?? [], null);
        $this->setIfExists('cuentas_bancarias', $data ?? [], null);
        $this->setIfExists('terminos_titulo', $data ?? [], null);
        $this->setIfExists('terminos', $data ?? [], null);
        $this->setIfExists('nota_pago_titulo', $data ?? [], null);
        $this->setIfExists('nota_pago_texto', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['ruc']) && (mb_strlen($this->container['ruc']) > 11)) {
            $invalidProperties[] = "invalid value for 'ruc', the character length must be smaller than or equal to 11.";
        }

        if (!is_null($this->container['ruc']) && (mb_strlen($this->container['ruc']) < 11)) {
            $invalidProperties[] = "invalid value for 'ruc', the character length must be bigger than or equal to 11.";
        }

        if (!is_null($this->container['razon_social']) && (mb_strlen($this->container['razon_social']) > 255)) {
            $invalidProperties[] = "invalid value for 'razon_social', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['razon_social']) && (mb_strlen($this->container['razon_social']) < 1)) {
            $invalidProperties[] = "invalid value for 'razon_social', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['nombre_comercial']) && (mb_strlen($this->container['nombre_comercial']) > 255)) {
            $invalidProperties[] = "invalid value for 'nombre_comercial', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['ubigeo']) && (mb_strlen($this->container['ubigeo']) > 6)) {
            $invalidProperties[] = "invalid value for 'ubigeo', the character length must be smaller than or equal to 6.";
        }

        if (!is_null($this->container['ubigeo']) && (mb_strlen($this->container['ubigeo']) < 6)) {
            $invalidProperties[] = "invalid value for 'ubigeo', the character length must be bigger than or equal to 6.";
        }

        if (!is_null($this->container['direccion']) && (mb_strlen($this->container['direccion']) > 500)) {
            $invalidProperties[] = "invalid value for 'direccion', the character length must be smaller than or equal to 500.";
        }

        if (!is_null($this->container['departamento']) && (mb_strlen($this->container['departamento']) > 100)) {
            $invalidProperties[] = "invalid value for 'departamento', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['provincia']) && (mb_strlen($this->container['provincia']) > 100)) {
            $invalidProperties[] = "invalid value for 'provincia', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['distrito']) && (mb_strlen($this->container['distrito']) > 100)) {
            $invalidProperties[] = "invalid value for 'distrito', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['urbanizacion']) && (mb_strlen($this->container['urbanizacion']) > 200)) {
            $invalidProperties[] = "invalid value for 'urbanizacion', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['telefono']) && (mb_strlen($this->container['telefono']) > 50)) {
            $invalidProperties[] = "invalid value for 'telefono', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['email']) && (mb_strlen($this->container['email']) > 120)) {
            $invalidProperties[] = "invalid value for 'email', the character length must be smaller than or equal to 120.";
        }

        if (!is_null($this->container['email']) && !preg_match("/^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$/", $this->container['email'])) {
            $invalidProperties[] = "invalid value for 'email', must be conform to the pattern /^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$/.";
        }

        if (!is_null($this->container['web']) && (mb_strlen($this->container['web']) > 120)) {
            $invalidProperties[] = "invalid value for 'web', the character length must be smaller than or equal to 120.";
        }

        if (!is_null($this->container['sol_user']) && (mb_strlen($this->container['sol_user']) > 50)) {
            $invalidProperties[] = "invalid value for 'sol_user', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['sol_password']) && (mb_strlen($this->container['sol_password']) > 100)) {
            $invalidProperties[] = "invalid value for 'sol_password', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['tenant_id']) && !preg_match("/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/", $this->container['tenant_id'])) {
            $invalidProperties[] = "invalid value for 'tenant_id', must be conform to the pattern /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/.";
        }

        if (!is_null($this->container['gre_client_id']) && (mb_strlen($this->container['gre_client_id']) > 100)) {
            $invalidProperties[] = "invalid value for 'gre_client_id', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['gre_client_secret']) && (mb_strlen($this->container['gre_client_secret']) > 255)) {
            $invalidProperties[] = "invalid value for 'gre_client_secret', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['cuentas_bancarias']) && (count($this->container['cuentas_bancarias']) > 6)) {
            $invalidProperties[] = "invalid value for 'cuentas_bancarias', number of items must be less than or equal to 6.";
        }

        if (!is_null($this->container['terminos_titulo']) && (mb_strlen($this->container['terminos_titulo']) > 120)) {
            $invalidProperties[] = "invalid value for 'terminos_titulo', the character length must be smaller than or equal to 120.";
        }

        if (!is_null($this->container['terminos']) && (count($this->container['terminos']) > 8)) {
            $invalidProperties[] = "invalid value for 'terminos', number of items must be less than or equal to 8.";
        }

        if (!is_null($this->container['nota_pago_titulo']) && (mb_strlen($this->container['nota_pago_titulo']) > 60)) {
            $invalidProperties[] = "invalid value for 'nota_pago_titulo', the character length must be smaller than or equal to 60.";
        }

        if (!is_null($this->container['nota_pago_texto']) && (mb_strlen($this->container['nota_pago_texto']) > 300)) {
            $invalidProperties[] = "invalid value for 'nota_pago_texto', the character length must be smaller than or equal to 300.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ruc
     *
     * @return string|null
     */
    public function getRuc()
    {
        return $this->container['ruc'];
    }

    /**
     * Sets ruc
     *
     * @param string|null $ruc ruc
     *
     * @return self
     */
    public function setRuc($ruc)
    {
        if (is_null($ruc)) {
            throw new \InvalidArgumentException('non-nullable ruc cannot be null');
        }
        if ((mb_strlen($ruc) > 11)) {
            throw new \InvalidArgumentException('invalid length for $ruc when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 11.');
        }
        if ((mb_strlen($ruc) < 11)) {
            throw new \InvalidArgumentException('invalid length for $ruc when calling ApiV1CompaniesIdPutRequest., must be bigger than or equal to 11.');
        }

        $this->container['ruc'] = $ruc;

        return $this;
    }

    /**
     * Gets razon_social
     *
     * @return string|null
     */
    public function getRazonSocial()
    {
        return $this->container['razon_social'];
    }

    /**
     * Sets razon_social
     *
     * @param string|null $razon_social razon_social
     *
     * @return self
     */
    public function setRazonSocial($razon_social)
    {
        if (is_null($razon_social)) {
            throw new \InvalidArgumentException('non-nullable razon_social cannot be null');
        }
        if ((mb_strlen($razon_social) > 255)) {
            throw new \InvalidArgumentException('invalid length for $razon_social when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($razon_social) < 1)) {
            throw new \InvalidArgumentException('invalid length for $razon_social when calling ApiV1CompaniesIdPutRequest., must be bigger than or equal to 1.');
        }

        $this->container['razon_social'] = $razon_social;

        return $this;
    }

    /**
     * Gets nombre_comercial
     *
     * @return string|null
     */
    public function getNombreComercial()
    {
        return $this->container['nombre_comercial'];
    }

    /**
     * Sets nombre_comercial
     *
     * @param string|null $nombre_comercial nombre_comercial
     *
     * @return self
     */
    public function setNombreComercial($nombre_comercial)
    {
        if (is_null($nombre_comercial)) {
            throw new \InvalidArgumentException('non-nullable nombre_comercial cannot be null');
        }
        if ((mb_strlen($nombre_comercial) > 255)) {
            throw new \InvalidArgumentException('invalid length for $nombre_comercial when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 255.');
        }

        $this->container['nombre_comercial'] = $nombre_comercial;

        return $this;
    }

    /**
     * Gets ubigeo
     *
     * @return string|null
     */
    public function getUbigeo()
    {
        return $this->container['ubigeo'];
    }

    /**
     * Sets ubigeo
     *
     * @param string|null $ubigeo ubigeo
     *
     * @return self
     */
    public function setUbigeo($ubigeo)
    {
        if (is_null($ubigeo)) {
            throw new \InvalidArgumentException('non-nullable ubigeo cannot be null');
        }
        if ((mb_strlen($ubigeo) > 6)) {
            throw new \InvalidArgumentException('invalid length for $ubigeo when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 6.');
        }
        if ((mb_strlen($ubigeo) < 6)) {
            throw new \InvalidArgumentException('invalid length for $ubigeo when calling ApiV1CompaniesIdPutRequest., must be bigger than or equal to 6.');
        }

        $this->container['ubigeo'] = $ubigeo;

        return $this;
    }

    /**
     * Gets direccion
     *
     * @return string|null
     */
    public function getDireccion()
    {
        return $this->container['direccion'];
    }

    /**
     * Sets direccion
     *
     * @param string|null $direccion direccion
     *
     * @return self
     */
    public function setDireccion($direccion)
    {
        if (is_null($direccion)) {
            throw new \InvalidArgumentException('non-nullable direccion cannot be null');
        }
        if ((mb_strlen($direccion) > 500)) {
            throw new \InvalidArgumentException('invalid length for $direccion when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 500.');
        }

        $this->container['direccion'] = $direccion;

        return $this;
    }

    /**
     * Gets departamento
     *
     * @return string|null
     */
    public function getDepartamento()
    {
        return $this->container['departamento'];
    }

    /**
     * Sets departamento
     *
     * @param string|null $departamento departamento
     *
     * @return self
     */
    public function setDepartamento($departamento)
    {
        if (is_null($departamento)) {
            throw new \InvalidArgumentException('non-nullable departamento cannot be null');
        }
        if ((mb_strlen($departamento) > 100)) {
            throw new \InvalidArgumentException('invalid length for $departamento when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 100.');
        }

        $this->container['departamento'] = $departamento;

        return $this;
    }

    /**
     * Gets provincia
     *
     * @return string|null
     */
    public function getProvincia()
    {
        return $this->container['provincia'];
    }

    /**
     * Sets provincia
     *
     * @param string|null $provincia provincia
     *
     * @return self
     */
    public function setProvincia($provincia)
    {
        if (is_null($provincia)) {
            throw new \InvalidArgumentException('non-nullable provincia cannot be null');
        }
        if ((mb_strlen($provincia) > 100)) {
            throw new \InvalidArgumentException('invalid length for $provincia when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 100.');
        }

        $this->container['provincia'] = $provincia;

        return $this;
    }

    /**
     * Gets distrito
     *
     * @return string|null
     */
    public function getDistrito()
    {
        return $this->container['distrito'];
    }

    /**
     * Sets distrito
     *
     * @param string|null $distrito distrito
     *
     * @return self
     */
    public function setDistrito($distrito)
    {
        if (is_null($distrito)) {
            throw new \InvalidArgumentException('non-nullable distrito cannot be null');
        }
        if ((mb_strlen($distrito) > 100)) {
            throw new \InvalidArgumentException('invalid length for $distrito when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 100.');
        }

        $this->container['distrito'] = $distrito;

        return $this;
    }

    /**
     * Gets urbanizacion
     *
     * @return string|null
     */
    public function getUrbanizacion()
    {
        return $this->container['urbanizacion'];
    }

    /**
     * Sets urbanizacion
     *
     * @param string|null $urbanizacion urbanizacion
     *
     * @return self
     */
    public function setUrbanizacion($urbanizacion)
    {
        if (is_null($urbanizacion)) {
            throw new \InvalidArgumentException('non-nullable urbanizacion cannot be null');
        }
        if ((mb_strlen($urbanizacion) > 200)) {
            throw new \InvalidArgumentException('invalid length for $urbanizacion when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 200.');
        }

        $this->container['urbanizacion'] = $urbanizacion;

        return $this;
    }

    /**
     * Gets telefono
     *
     * @return string|null
     */
    public function getTelefono()
    {
        return $this->container['telefono'];
    }

    /**
     * Sets telefono
     *
     * @param string|null $telefono telefono
     *
     * @return self
     */
    public function setTelefono($telefono)
    {
        if (is_null($telefono)) {
            throw new \InvalidArgumentException('non-nullable telefono cannot be null');
        }
        if ((mb_strlen($telefono) > 50)) {
            throw new \InvalidArgumentException('invalid length for $telefono when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 50.');
        }

        $this->container['telefono'] = $telefono;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        if ((mb_strlen($email) > 120)) {
            throw new \InvalidArgumentException('invalid length for $email when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 120.');
        }
        if ((!preg_match("/^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$/", ObjectSerializer::toString($email)))) {
            throw new \InvalidArgumentException("invalid value for \$email when calling ApiV1CompaniesIdPutRequest., must conform to the pattern /^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$/.");
        }

        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets web
     *
     * @return string|null
     */
    public function getWeb()
    {
        return $this->container['web'];
    }

    /**
     * Sets web
     *
     * @param string|null $web web
     *
     * @return self
     */
    public function setWeb($web)
    {
        if (is_null($web)) {
            array_push($this->openAPINullablesSetToNull, 'web');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('web', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($web) && (mb_strlen($web) > 120)) {
            throw new \InvalidArgumentException('invalid length for $web when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 120.');
        }

        $this->container['web'] = $web;

        return $this;
    }

    /**
     * Gets sol_user
     *
     * @return string|null
     */
    public function getSolUser()
    {
        return $this->container['sol_user'];
    }

    /**
     * Sets sol_user
     *
     * @param string|null $sol_user sol_user
     *
     * @return self
     */
    public function setSolUser($sol_user)
    {
        if (is_null($sol_user)) {
            throw new \InvalidArgumentException('non-nullable sol_user cannot be null');
        }
        if ((mb_strlen($sol_user) > 50)) {
            throw new \InvalidArgumentException('invalid length for $sol_user when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 50.');
        }

        $this->container['sol_user'] = $sol_user;

        return $this;
    }

    /**
     * Gets sol_password
     *
     * @return string|null
     */
    public function getSolPassword()
    {
        return $this->container['sol_password'];
    }

    /**
     * Sets sol_password
     *
     * @param string|null $sol_password sol_password
     *
     * @return self
     */
    public function setSolPassword($sol_password)
    {
        if (is_null($sol_password)) {
            throw new \InvalidArgumentException('non-nullable sol_password cannot be null');
        }
        if ((mb_strlen($sol_password) > 100)) {
            throw new \InvalidArgumentException('invalid length for $sol_password when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 100.');
        }

        $this->container['sol_password'] = $sol_password;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return string|null
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param string|null $tenant_id tenant_id
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }

        if ((!preg_match("/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/", ObjectSerializer::toString($tenant_id)))) {
            throw new \InvalidArgumentException("invalid value for \$tenant_id when calling ApiV1CompaniesIdPutRequest., must conform to the pattern /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/.");
        }

        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets gre_client_id
     *
     * @return string|null
     */
    public function getGreClientId()
    {
        return $this->container['gre_client_id'];
    }

    /**
     * Sets gre_client_id
     *
     * @param string|null $gre_client_id gre_client_id
     *
     * @return self
     */
    public function setGreClientId($gre_client_id)
    {
        if (is_null($gre_client_id)) {
            throw new \InvalidArgumentException('non-nullable gre_client_id cannot be null');
        }
        if ((mb_strlen($gre_client_id) > 100)) {
            throw new \InvalidArgumentException('invalid length for $gre_client_id when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 100.');
        }

        $this->container['gre_client_id'] = $gre_client_id;

        return $this;
    }

    /**
     * Gets gre_client_secret
     *
     * @return string|null
     */
    public function getGreClientSecret()
    {
        return $this->container['gre_client_secret'];
    }

    /**
     * Sets gre_client_secret
     *
     * @param string|null $gre_client_secret gre_client_secret
     *
     * @return self
     */
    public function setGreClientSecret($gre_client_secret)
    {
        if (is_null($gre_client_secret)) {
            throw new \InvalidArgumentException('non-nullable gre_client_secret cannot be null');
        }
        if ((mb_strlen($gre_client_secret) > 255)) {
            throw new \InvalidArgumentException('invalid length for $gre_client_secret when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 255.');
        }

        $this->container['gre_client_secret'] = $gre_client_secret;

        return $this;
    }

    /**
     * Gets sunat_production
     *
     * @return bool|null
     */
    public function getSunatProduction()
    {
        return $this->container['sunat_production'];
    }

    /**
     * Sets sunat_production
     *
     * @param bool|null $sunat_production sunat_production
     *
     * @return self
     */
    public function setSunatProduction($sunat_production)
    {
        if (is_null($sunat_production)) {
            throw new \InvalidArgumentException('non-nullable sunat_production cannot be null');
        }
        $this->container['sunat_production'] = $sunat_production;

        return $this;
    }

    /**
     * Gets cuentas_bancarias
     *
     * @return \Intifact\Sdk\Model\ApiV1CompaniesPostRequestCuentasBancariasInner[]|null
     */
    public function getCuentasBancarias()
    {
        return $this->container['cuentas_bancarias'];
    }

    /**
     * Sets cuentas_bancarias
     *
     * @param \Intifact\Sdk\Model\ApiV1CompaniesPostRequestCuentasBancariasInner[]|null $cuentas_bancarias cuentas_bancarias
     *
     * @return self
     */
    public function setCuentasBancarias($cuentas_bancarias)
    {
        if (is_null($cuentas_bancarias)) {
            throw new \InvalidArgumentException('non-nullable cuentas_bancarias cannot be null');
        }
        if ((count($cuentas_bancarias) > 6)) {
            throw new \InvalidArgumentException('invalid value for $cuentas_bancarias when calling ApiV1CompaniesIdPutRequest., number of items must be less than or equal to 6.');
        }
        $this->container['cuentas_bancarias'] = $cuentas_bancarias;

        return $this;
    }

    /**
     * Gets terminos_titulo
     *
     * @return string|null
     */
    public function getTerminosTitulo()
    {
        return $this->container['terminos_titulo'];
    }

    /**
     * Sets terminos_titulo
     *
     * @param string|null $terminos_titulo terminos_titulo
     *
     * @return self
     */
    public function setTerminosTitulo($terminos_titulo)
    {
        if (is_null($terminos_titulo)) {
            array_push($this->openAPINullablesSetToNull, 'terminos_titulo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('terminos_titulo', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($terminos_titulo) && (mb_strlen($terminos_titulo) > 120)) {
            throw new \InvalidArgumentException('invalid length for $terminos_titulo when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 120.');
        }

        $this->container['terminos_titulo'] = $terminos_titulo;

        return $this;
    }

    /**
     * Gets terminos
     *
     * @return string[]|null
     */
    public function getTerminos()
    {
        return $this->container['terminos'];
    }

    /**
     * Sets terminos
     *
     * @param string[]|null $terminos terminos
     *
     * @return self
     */
    public function setTerminos($terminos)
    {
        if (is_null($terminos)) {
            throw new \InvalidArgumentException('non-nullable terminos cannot be null');
        }
        if ((count($terminos) > 8)) {
            throw new \InvalidArgumentException('invalid value for $terminos when calling ApiV1CompaniesIdPutRequest., number of items must be less than or equal to 8.');
        }
        $this->container['terminos'] = $terminos;

        return $this;
    }

    /**
     * Gets nota_pago_titulo
     *
     * @return string|null
     */
    public function getNotaPagoTitulo()
    {
        return $this->container['nota_pago_titulo'];
    }

    /**
     * Sets nota_pago_titulo
     *
     * @param string|null $nota_pago_titulo nota_pago_titulo
     *
     * @return self
     */
    public function setNotaPagoTitulo($nota_pago_titulo)
    {
        if (is_null($nota_pago_titulo)) {
            array_push($this->openAPINullablesSetToNull, 'nota_pago_titulo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nota_pago_titulo', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($nota_pago_titulo) && (mb_strlen($nota_pago_titulo) > 60)) {
            throw new \InvalidArgumentException('invalid length for $nota_pago_titulo when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 60.');
        }

        $this->container['nota_pago_titulo'] = $nota_pago_titulo;

        return $this;
    }

    /**
     * Gets nota_pago_texto
     *
     * @return string|null
     */
    public function getNotaPagoTexto()
    {
        return $this->container['nota_pago_texto'];
    }

    /**
     * Sets nota_pago_texto
     *
     * @param string|null $nota_pago_texto nota_pago_texto
     *
     * @return self
     */
    public function setNotaPagoTexto($nota_pago_texto)
    {
        if (is_null($nota_pago_texto)) {
            array_push($this->openAPINullablesSetToNull, 'nota_pago_texto');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nota_pago_texto', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($nota_pago_texto) && (mb_strlen($nota_pago_texto) > 300)) {
            throw new \InvalidArgumentException('invalid length for $nota_pago_texto when calling ApiV1CompaniesIdPutRequest., must be smaller than or equal to 300.');
        }

        $this->container['nota_pago_texto'] = $nota_pago_texto;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


