<?php
/**
 * ApiV1DespatchSendPostRequestIndicadores
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API de Facturación Electrónica SUNAT
 *
 * API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Intifact\Sdk\Model;

use \ArrayAccess;
use \Intifact\Sdk\ObjectSerializer;

/**
 * ApiV1DespatchSendPostRequestIndicadores Class Doc Comment
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApiV1DespatchSendPostRequestIndicadores implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = '_api_v1_despatch_send_post_request_indicadores';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'transbordo_programado' => 'bool',
        'vehiculo_m1_l' => 'bool',
        'retorno_vehiculo_envase_vacio' => 'bool',
        'retorno_vehiculo_vacio' => 'bool',
        'traslado_total_dam_ds' => 'bool',
        'registro_transportista' => 'bool',
        'traslado_contenedor_manifiesto' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'transbordo_programado' => null,
        'vehiculo_m1_l' => null,
        'retorno_vehiculo_envase_vacio' => null,
        'retorno_vehiculo_vacio' => null,
        'traslado_total_dam_ds' => null,
        'registro_transportista' => null,
        'traslado_contenedor_manifiesto' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'transbordo_programado' => false,
        'vehiculo_m1_l' => false,
        'retorno_vehiculo_envase_vacio' => false,
        'retorno_vehiculo_vacio' => false,
        'traslado_total_dam_ds' => false,
        'registro_transportista' => false,
        'traslado_contenedor_manifiesto' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'transbordo_programado' => 'transbordoProgramado',
        'vehiculo_m1_l' => 'vehiculoM1L',
        'retorno_vehiculo_envase_vacio' => 'retornoVehiculoEnvaseVacio',
        'retorno_vehiculo_vacio' => 'retornoVehiculoVacio',
        'traslado_total_dam_ds' => 'trasladoTotalDamDs',
        'registro_transportista' => 'registroTransportista',
        'traslado_contenedor_manifiesto' => 'trasladoContenedorManifiesto'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'transbordo_programado' => 'setTransbordoProgramado',
        'vehiculo_m1_l' => 'setVehiculoM1L',
        'retorno_vehiculo_envase_vacio' => 'setRetornoVehiculoEnvaseVacio',
        'retorno_vehiculo_vacio' => 'setRetornoVehiculoVacio',
        'traslado_total_dam_ds' => 'setTrasladoTotalDamDs',
        'registro_transportista' => 'setRegistroTransportista',
        'traslado_contenedor_manifiesto' => 'setTrasladoContenedorManifiesto'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'transbordo_programado' => 'getTransbordoProgramado',
        'vehiculo_m1_l' => 'getVehiculoM1L',
        'retorno_vehiculo_envase_vacio' => 'getRetornoVehiculoEnvaseVacio',
        'retorno_vehiculo_vacio' => 'getRetornoVehiculoVacio',
        'traslado_total_dam_ds' => 'getTrasladoTotalDamDs',
        'registro_transportista' => 'getRegistroTransportista',
        'traslado_contenedor_manifiesto' => 'getTrasladoContenedorManifiesto'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('transbordo_programado', $data ?? [], null);
        $this->setIfExists('vehiculo_m1_l', $data ?? [], null);
        $this->setIfExists('retorno_vehiculo_envase_vacio', $data ?? [], null);
        $this->setIfExists('retorno_vehiculo_vacio', $data ?? [], null);
        $this->setIfExists('traslado_total_dam_ds', $data ?? [], null);
        $this->setIfExists('registro_transportista', $data ?? [], null);
        $this->setIfExists('traslado_contenedor_manifiesto', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets transbordo_programado
     *
     * @return bool|null
     */
    public function getTransbordoProgramado()
    {
        return $this->container['transbordo_programado'];
    }

    /**
     * Sets transbordo_programado
     *
     * @param bool|null $transbordo_programado transbordo_programado
     *
     * @return self
     */
    public function setTransbordoProgramado($transbordo_programado)
    {
        if (is_null($transbordo_programado)) {
            throw new \InvalidArgumentException('non-nullable transbordo_programado cannot be null');
        }
        $this->container['transbordo_programado'] = $transbordo_programado;

        return $this;
    }

    /**
     * Gets vehiculo_m1_l
     *
     * @return bool|null
     */
    public function getVehiculoM1L()
    {
        return $this->container['vehiculo_m1_l'];
    }

    /**
     * Sets vehiculo_m1_l
     *
     * @param bool|null $vehiculo_m1_l vehiculo_m1_l
     *
     * @return self
     */
    public function setVehiculoM1L($vehiculo_m1_l)
    {
        if (is_null($vehiculo_m1_l)) {
            throw new \InvalidArgumentException('non-nullable vehiculo_m1_l cannot be null');
        }
        $this->container['vehiculo_m1_l'] = $vehiculo_m1_l;

        return $this;
    }

    /**
     * Gets retorno_vehiculo_envase_vacio
     *
     * @return bool|null
     */
    public function getRetornoVehiculoEnvaseVacio()
    {
        return $this->container['retorno_vehiculo_envase_vacio'];
    }

    /**
     * Sets retorno_vehiculo_envase_vacio
     *
     * @param bool|null $retorno_vehiculo_envase_vacio retorno_vehiculo_envase_vacio
     *
     * @return self
     */
    public function setRetornoVehiculoEnvaseVacio($retorno_vehiculo_envase_vacio)
    {
        if (is_null($retorno_vehiculo_envase_vacio)) {
            throw new \InvalidArgumentException('non-nullable retorno_vehiculo_envase_vacio cannot be null');
        }
        $this->container['retorno_vehiculo_envase_vacio'] = $retorno_vehiculo_envase_vacio;

        return $this;
    }

    /**
     * Gets retorno_vehiculo_vacio
     *
     * @return bool|null
     */
    public function getRetornoVehiculoVacio()
    {
        return $this->container['retorno_vehiculo_vacio'];
    }

    /**
     * Sets retorno_vehiculo_vacio
     *
     * @param bool|null $retorno_vehiculo_vacio retorno_vehiculo_vacio
     *
     * @return self
     */
    public function setRetornoVehiculoVacio($retorno_vehiculo_vacio)
    {
        if (is_null($retorno_vehiculo_vacio)) {
            throw new \InvalidArgumentException('non-nullable retorno_vehiculo_vacio cannot be null');
        }
        $this->container['retorno_vehiculo_vacio'] = $retorno_vehiculo_vacio;

        return $this;
    }

    /**
     * Gets traslado_total_dam_ds
     *
     * @return bool|null
     */
    public function getTrasladoTotalDamDs()
    {
        return $this->container['traslado_total_dam_ds'];
    }

    /**
     * Sets traslado_total_dam_ds
     *
     * @param bool|null $traslado_total_dam_ds traslado_total_dam_ds
     *
     * @return self
     */
    public function setTrasladoTotalDamDs($traslado_total_dam_ds)
    {
        if (is_null($traslado_total_dam_ds)) {
            throw new \InvalidArgumentException('non-nullable traslado_total_dam_ds cannot be null');
        }
        $this->container['traslado_total_dam_ds'] = $traslado_total_dam_ds;

        return $this;
    }

    /**
     * Gets registro_transportista
     *
     * @return bool|null
     */
    public function getRegistroTransportista()
    {
        return $this->container['registro_transportista'];
    }

    /**
     * Sets registro_transportista
     *
     * @param bool|null $registro_transportista registro_transportista
     *
     * @return self
     */
    public function setRegistroTransportista($registro_transportista)
    {
        if (is_null($registro_transportista)) {
            throw new \InvalidArgumentException('non-nullable registro_transportista cannot be null');
        }
        $this->container['registro_transportista'] = $registro_transportista;

        return $this;
    }

    /**
     * Gets traslado_contenedor_manifiesto
     *
     * @return bool|null
     */
    public function getTrasladoContenedorManifiesto()
    {
        return $this->container['traslado_contenedor_manifiesto'];
    }

    /**
     * Sets traslado_contenedor_manifiesto
     *
     * @param bool|null $traslado_contenedor_manifiesto traslado_contenedor_manifiesto
     *
     * @return self
     */
    public function setTrasladoContenedorManifiesto($traslado_contenedor_manifiesto)
    {
        if (is_null($traslado_contenedor_manifiesto)) {
            throw new \InvalidArgumentException('non-nullable traslado_contenedor_manifiesto cannot be null');
        }
        $this->container['traslado_contenedor_manifiesto'] = $traslado_contenedor_manifiesto;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


