<?php
/**
 * ListDocuments200ResponseDataInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API de Facturación Electrónica SUNAT
 *
 * API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Intifact\Sdk\Model;

use \ArrayAccess;
use \Intifact\Sdk\ObjectSerializer;

/**
 * ListDocuments200ResponseDataInner Class Doc Comment
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ListDocuments200ResponseDataInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'listDocuments_200_response_data_inner';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'env' => 'string',
        'tipo_doc' => 'string',
        'serie' => 'string',
        'correlativo' => 'string',
        'fecha_emision' => 'string',
        'tipo_moneda' => 'string',
        'cliente_num_doc' => 'string',
        'cliente_razon_social' => 'string',
        'monto_imp_venta' => 'string',
        'monto_igv' => 'string',
        'estado_sunat' => 'string',
        'codigo_respuesta' => 'string',
        'descripcion_respuesta' => 'string',
        'hash_cdr' => 'string',
        'created_at' => 'string',
        'company' => '\Intifact\Sdk\Model\ListDocuments200ResponseDataInnerCompany'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'env' => null,
        'tipo_doc' => null,
        'serie' => null,
        'correlativo' => null,
        'fecha_emision' => null,
        'tipo_moneda' => null,
        'cliente_num_doc' => null,
        'cliente_razon_social' => null,
        'monto_imp_venta' => null,
        'monto_igv' => null,
        'estado_sunat' => null,
        'codigo_respuesta' => null,
        'descripcion_respuesta' => null,
        'hash_cdr' => null,
        'created_at' => null,
        'company' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => true,
        'env' => false,
        'tipo_doc' => true,
        'serie' => true,
        'correlativo' => true,
        'fecha_emision' => true,
        'tipo_moneda' => true,
        'cliente_num_doc' => true,
        'cliente_razon_social' => true,
        'monto_imp_venta' => true,
        'monto_igv' => true,
        'estado_sunat' => true,
        'codigo_respuesta' => true,
        'descripcion_respuesta' => true,
        'hash_cdr' => true,
        'created_at' => true,
        'company' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'env' => 'env',
        'tipo_doc' => 'tipoDoc',
        'serie' => 'serie',
        'correlativo' => 'correlativo',
        'fecha_emision' => 'fechaEmision',
        'tipo_moneda' => 'tipoMoneda',
        'cliente_num_doc' => 'clienteNumDoc',
        'cliente_razon_social' => 'clienteRazonSocial',
        'monto_imp_venta' => 'montoImpVenta',
        'monto_igv' => 'montoIgv',
        'estado_sunat' => 'estadoSunat',
        'codigo_respuesta' => 'codigoRespuesta',
        'descripcion_respuesta' => 'descripcionRespuesta',
        'hash_cdr' => 'hashCdr',
        'created_at' => 'createdAt',
        'company' => 'company'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'env' => 'setEnv',
        'tipo_doc' => 'setTipoDoc',
        'serie' => 'setSerie',
        'correlativo' => 'setCorrelativo',
        'fecha_emision' => 'setFechaEmision',
        'tipo_moneda' => 'setTipoMoneda',
        'cliente_num_doc' => 'setClienteNumDoc',
        'cliente_razon_social' => 'setClienteRazonSocial',
        'monto_imp_venta' => 'setMontoImpVenta',
        'monto_igv' => 'setMontoIgv',
        'estado_sunat' => 'setEstadoSunat',
        'codigo_respuesta' => 'setCodigoRespuesta',
        'descripcion_respuesta' => 'setDescripcionRespuesta',
        'hash_cdr' => 'setHashCdr',
        'created_at' => 'setCreatedAt',
        'company' => 'setCompany'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'env' => 'getEnv',
        'tipo_doc' => 'getTipoDoc',
        'serie' => 'getSerie',
        'correlativo' => 'getCorrelativo',
        'fecha_emision' => 'getFechaEmision',
        'tipo_moneda' => 'getTipoMoneda',
        'cliente_num_doc' => 'getClienteNumDoc',
        'cliente_razon_social' => 'getClienteRazonSocial',
        'monto_imp_venta' => 'getMontoImpVenta',
        'monto_igv' => 'getMontoIgv',
        'estado_sunat' => 'getEstadoSunat',
        'codigo_respuesta' => 'getCodigoRespuesta',
        'descripcion_respuesta' => 'getDescripcionRespuesta',
        'hash_cdr' => 'getHashCdr',
        'created_at' => 'getCreatedAt',
        'company' => 'getCompany'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ENV_LIVE = 'live';
    public const ENV_TEST = 'test';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEnvAllowableValues()
    {
        return [
            self::ENV_LIVE,
            self::ENV_TEST,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('env', $data ?? [], null);
        $this->setIfExists('tipo_doc', $data ?? [], null);
        $this->setIfExists('serie', $data ?? [], null);
        $this->setIfExists('correlativo', $data ?? [], null);
        $this->setIfExists('fecha_emision', $data ?? [], null);
        $this->setIfExists('tipo_moneda', $data ?? [], null);
        $this->setIfExists('cliente_num_doc', $data ?? [], null);
        $this->setIfExists('cliente_razon_social', $data ?? [], null);
        $this->setIfExists('monto_imp_venta', $data ?? [], null);
        $this->setIfExists('monto_igv', $data ?? [], null);
        $this->setIfExists('estado_sunat', $data ?? [], null);
        $this->setIfExists('codigo_respuesta', $data ?? [], null);
        $this->setIfExists('descripcion_respuesta', $data ?? [], null);
        $this->setIfExists('hash_cdr', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('company', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null && !$this->isNullableSetToNull('id')) {
            $invalidProperties[] = "'id' is required";
        }
        if ($this->container['env'] === null) {
            $invalidProperties[] = "'env' can't be null";
        }
        $allowedValues = $this->getEnvAllowableValues();
        if (!is_null($this->container['env']) && !in_array($this->container['env'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'env', must be one of '%s'",
                $this->container['env'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['tipo_doc'] === null && !$this->isNullableSetToNull('tipo_doc')) {
            $invalidProperties[] = "'tipo_doc' is required";
        }
        if ($this->container['serie'] === null && !$this->isNullableSetToNull('serie')) {
            $invalidProperties[] = "'serie' is required";
        }
        if ($this->container['correlativo'] === null && !$this->isNullableSetToNull('correlativo')) {
            $invalidProperties[] = "'correlativo' is required";
        }
        if ($this->container['fecha_emision'] === null && !$this->isNullableSetToNull('fecha_emision')) {
            $invalidProperties[] = "'fecha_emision' is required";
        }
        if ($this->container['tipo_moneda'] === null && !$this->isNullableSetToNull('tipo_moneda')) {
            $invalidProperties[] = "'tipo_moneda' is required";
        }
        if ($this->container['cliente_num_doc'] === null && !$this->isNullableSetToNull('cliente_num_doc')) {
            $invalidProperties[] = "'cliente_num_doc' is required";
        }
        if ($this->container['cliente_razon_social'] === null && !$this->isNullableSetToNull('cliente_razon_social')) {
            $invalidProperties[] = "'cliente_razon_social' is required";
        }
        if ($this->container['monto_imp_venta'] === null && !$this->isNullableSetToNull('monto_imp_venta')) {
            $invalidProperties[] = "'monto_imp_venta' is required";
        }
        if ($this->container['estado_sunat'] === null && !$this->isNullableSetToNull('estado_sunat')) {
            $invalidProperties[] = "'estado_sunat' is required";
        }
        if ($this->container['codigo_respuesta'] === null && !$this->isNullableSetToNull('codigo_respuesta')) {
            $invalidProperties[] = "'codigo_respuesta' is required";
        }
        if ($this->container['hash_cdr'] === null && !$this->isNullableSetToNull('hash_cdr')) {
            $invalidProperties[] = "'hash_cdr' is required";
        }
        if ($this->container['created_at'] === null && !$this->isNullableSetToNull('created_at')) {
            $invalidProperties[] = "'created_at' is required";
        }
        if ($this->container['company'] === null) {
            $invalidProperties[] = "'company' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets env
     *
     * @return string
     */
    public function getEnv()
    {
        return $this->container['env'];
    }

    /**
     * Sets env
     *
     * @param string $env env
     *
     * @return self
     */
    public function setEnv($env)
    {
        if (is_null($env)) {
            throw new \InvalidArgumentException('non-nullable env cannot be null');
        }
        $allowedValues = $this->getEnvAllowableValues();
        if (!in_array($env, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'env', must be one of '%s'",
                    $env,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['env'] = $env;

        return $this;
    }

    /**
     * Gets tipo_doc
     *
     * @return string|null
     */
    public function getTipoDoc()
    {
        return $this->container['tipo_doc'];
    }

    /**
     * Sets tipo_doc
     *
     * @param string|null $tipo_doc tipo_doc
     *
     * @return self
     */
    public function setTipoDoc($tipo_doc)
    {
        if (is_null($tipo_doc)) {
            array_push($this->openAPINullablesSetToNull, 'tipo_doc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tipo_doc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tipo_doc'] = $tipo_doc;

        return $this;
    }

    /**
     * Gets serie
     *
     * @return string|null
     */
    public function getSerie()
    {
        return $this->container['serie'];
    }

    /**
     * Sets serie
     *
     * @param string|null $serie serie
     *
     * @return self
     */
    public function setSerie($serie)
    {
        if (is_null($serie)) {
            array_push($this->openAPINullablesSetToNull, 'serie');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('serie', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['serie'] = $serie;

        return $this;
    }

    /**
     * Gets correlativo
     *
     * @return string|null
     */
    public function getCorrelativo()
    {
        return $this->container['correlativo'];
    }

    /**
     * Sets correlativo
     *
     * @param string|null $correlativo correlativo
     *
     * @return self
     */
    public function setCorrelativo($correlativo)
    {
        if (is_null($correlativo)) {
            array_push($this->openAPINullablesSetToNull, 'correlativo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('correlativo', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['correlativo'] = $correlativo;

        return $this;
    }

    /**
     * Gets fecha_emision
     *
     * @return string|null
     */
    public function getFechaEmision()
    {
        return $this->container['fecha_emision'];
    }

    /**
     * Sets fecha_emision
     *
     * @param string|null $fecha_emision fecha_emision
     *
     * @return self
     */
    public function setFechaEmision($fecha_emision)
    {
        if (is_null($fecha_emision)) {
            array_push($this->openAPINullablesSetToNull, 'fecha_emision');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fecha_emision', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fecha_emision'] = $fecha_emision;

        return $this;
    }

    /**
     * Gets tipo_moneda
     *
     * @return string|null
     */
    public function getTipoMoneda()
    {
        return $this->container['tipo_moneda'];
    }

    /**
     * Sets tipo_moneda
     *
     * @param string|null $tipo_moneda tipo_moneda
     *
     * @return self
     */
    public function setTipoMoneda($tipo_moneda)
    {
        if (is_null($tipo_moneda)) {
            array_push($this->openAPINullablesSetToNull, 'tipo_moneda');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tipo_moneda', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tipo_moneda'] = $tipo_moneda;

        return $this;
    }

    /**
     * Gets cliente_num_doc
     *
     * @return string|null
     */
    public function getClienteNumDoc()
    {
        return $this->container['cliente_num_doc'];
    }

    /**
     * Sets cliente_num_doc
     *
     * @param string|null $cliente_num_doc cliente_num_doc
     *
     * @return self
     */
    public function setClienteNumDoc($cliente_num_doc)
    {
        if (is_null($cliente_num_doc)) {
            array_push($this->openAPINullablesSetToNull, 'cliente_num_doc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cliente_num_doc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cliente_num_doc'] = $cliente_num_doc;

        return $this;
    }

    /**
     * Gets cliente_razon_social
     *
     * @return string|null
     */
    public function getClienteRazonSocial()
    {
        return $this->container['cliente_razon_social'];
    }

    /**
     * Sets cliente_razon_social
     *
     * @param string|null $cliente_razon_social cliente_razon_social
     *
     * @return self
     */
    public function setClienteRazonSocial($cliente_razon_social)
    {
        if (is_null($cliente_razon_social)) {
            array_push($this->openAPINullablesSetToNull, 'cliente_razon_social');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cliente_razon_social', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cliente_razon_social'] = $cliente_razon_social;

        return $this;
    }

    /**
     * Gets monto_imp_venta
     *
     * @return string|null
     */
    public function getMontoImpVenta()
    {
        return $this->container['monto_imp_venta'];
    }

    /**
     * Sets monto_imp_venta
     *
     * @param string|null $monto_imp_venta monto_imp_venta
     *
     * @return self
     */
    public function setMontoImpVenta($monto_imp_venta)
    {
        if (is_null($monto_imp_venta)) {
            array_push($this->openAPINullablesSetToNull, 'monto_imp_venta');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('monto_imp_venta', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['monto_imp_venta'] = $monto_imp_venta;

        return $this;
    }

    /**
     * Gets monto_igv
     *
     * @return string|null
     */
    public function getMontoIgv()
    {
        return $this->container['monto_igv'];
    }

    /**
     * Sets monto_igv
     *
     * @param string|null $monto_igv monto_igv
     *
     * @return self
     */
    public function setMontoIgv($monto_igv)
    {
        if (is_null($monto_igv)) {
            array_push($this->openAPINullablesSetToNull, 'monto_igv');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('monto_igv', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['monto_igv'] = $monto_igv;

        return $this;
    }

    /**
     * Gets estado_sunat
     *
     * @return string|null
     */
    public function getEstadoSunat()
    {
        return $this->container['estado_sunat'];
    }

    /**
     * Sets estado_sunat
     *
     * @param string|null $estado_sunat estado_sunat
     *
     * @return self
     */
    public function setEstadoSunat($estado_sunat)
    {
        if (is_null($estado_sunat)) {
            array_push($this->openAPINullablesSetToNull, 'estado_sunat');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('estado_sunat', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['estado_sunat'] = $estado_sunat;

        return $this;
    }

    /**
     * Gets codigo_respuesta
     *
     * @return string|null
     */
    public function getCodigoRespuesta()
    {
        return $this->container['codigo_respuesta'];
    }

    /**
     * Sets codigo_respuesta
     *
     * @param string|null $codigo_respuesta codigo_respuesta
     *
     * @return self
     */
    public function setCodigoRespuesta($codigo_respuesta)
    {
        if (is_null($codigo_respuesta)) {
            array_push($this->openAPINullablesSetToNull, 'codigo_respuesta');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('codigo_respuesta', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['codigo_respuesta'] = $codigo_respuesta;

        return $this;
    }

    /**
     * Gets descripcion_respuesta
     *
     * @return string|null
     */
    public function getDescripcionRespuesta()
    {
        return $this->container['descripcion_respuesta'];
    }

    /**
     * Sets descripcion_respuesta
     *
     * @param string|null $descripcion_respuesta descripcion_respuesta
     *
     * @return self
     */
    public function setDescripcionRespuesta($descripcion_respuesta)
    {
        if (is_null($descripcion_respuesta)) {
            array_push($this->openAPINullablesSetToNull, 'descripcion_respuesta');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('descripcion_respuesta', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['descripcion_respuesta'] = $descripcion_respuesta;

        return $this;
    }

    /**
     * Gets hash_cdr
     *
     * @return string|null
     */
    public function getHashCdr()
    {
        return $this->container['hash_cdr'];
    }

    /**
     * Sets hash_cdr
     *
     * @param string|null $hash_cdr hash_cdr
     *
     * @return self
     */
    public function setHashCdr($hash_cdr)
    {
        if (is_null($hash_cdr)) {
            array_push($this->openAPINullablesSetToNull, 'hash_cdr');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('hash_cdr', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['hash_cdr'] = $hash_cdr;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            array_push($this->openAPINullablesSetToNull, 'created_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('created_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets company
     *
     * @return \Intifact\Sdk\Model\ListDocuments200ResponseDataInnerCompany
     */
    public function getCompany()
    {
        return $this->container['company'];
    }

    /**
     * Sets company
     *
     * @param \Intifact\Sdk\Model\ListDocuments200ResponseDataInnerCompany $company company
     *
     * @return self
     */
    public function setCompany($company)
    {
        if (is_null($company)) {
            throw new \InvalidArgumentException('non-nullable company cannot be null');
        }
        $this->container['company'] = $company;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


