<?php
/**
 * ApiV1NoteSendPostRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API de Facturación Electrónica SUNAT
 *
 * API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Intifact\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ApiV1NoteSendPostRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ApiV1NoteSendPostRequest
 * @package     Intifact\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ApiV1NoteSendPostRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ApiV1NoteSendPostRequest"
     */
    public function testApiV1NoteSendPostRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_operacion"
     */
    public function testPropertyTipoOperacion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_doc"
     */
    public function testPropertyTipoDoc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "serie"
     */
    public function testPropertySerie()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "correlativo"
     */
    public function testPropertyCorrelativo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_moneda"
     */
    public function testPropertyTipoMoneda()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fecha_emision"
     */
    public function testPropertyFechaEmision()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "empresa_ruc"
     */
    public function testPropertyEmpresaRuc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "establecimiento_codigo"
     */
    public function testPropertyEstablecimientoCodigo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cliente_tipo_doc"
     */
    public function testPropertyClienteTipoDoc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cliente_num_doc"
     */
    public function testPropertyClienteNumDoc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cliente_razon_social"
     */
    public function testPropertyClienteRazonSocial()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cliente_direccion"
     */
    public function testPropertyClienteDireccion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cliente_distrito"
     */
    public function testPropertyClienteDistrito()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cliente_provincia"
     */
    public function testPropertyClienteProvincia()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cliente_departamento"
     */
    public function testPropertyClienteDepartamento()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "afectado_tipo_doc"
     */
    public function testPropertyAfectadoTipoDoc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "afectado_num_doc"
     */
    public function testPropertyAfectadoNumDoc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "motivo_cod"
     */
    public function testPropertyMotivoCod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "motivo_des"
     */
    public function testPropertyMotivoDes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "monto_oper_gravadas"
     */
    public function testPropertyMontoOperGravadas()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "monto_oper_exoneradas"
     */
    public function testPropertyMontoOperExoneradas()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "monto_oper_inafectas"
     */
    public function testPropertyMontoOperInafectas()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "monto_igv"
     */
    public function testPropertyMontoIgv()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_impuestos"
     */
    public function testPropertyTotalImpuestos()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valor_venta"
     */
    public function testPropertyValorVenta()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sub_total"
     */
    public function testPropertySubTotal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "monto_imp_venta"
     */
    public function testPropertyMontoImpVenta()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "descuento_global"
     */
    public function testPropertyDescuentoGlobal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "descuento_global_base"
     */
    public function testPropertyDescuentoGlobalBase()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "detalle"
     */
    public function testPropertyDetalle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "leyendas"
     */
    public function testPropertyLeyendas()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "observacion"
     */
    public function testPropertyObservacion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
