<?php
/**
 * ExportProductoSunat200ResponseDataItemsInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API de Facturación Electrónica SUNAT
 *
 * API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Intifact\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ExportProductoSunat200ResponseDataItemsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description ExportProductoSunat200ResponseDataItemsInner
 * @package     Intifact\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ExportProductoSunat200ResponseDataItemsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ExportProductoSunat200ResponseDataItemsInner"
     */
    public function testExportProductoSunat200ResponseDataItemsInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "codigo"
     */
    public function testPropertyCodigo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "descripcion"
     */
    public function testPropertyDescripcion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nivel"
     */
    public function testPropertyNivel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "clase_codigo"
     */
    public function testPropertyClaseCodigo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "familia"
     */
    public function testPropertyFamilia()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "segmento"
     */
    public function testPropertySegmento()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
