<?php
/**
 * ListDocuments200ResponseDataInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API de Facturación Electrónica SUNAT
 *
 * API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Intifact\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ListDocuments200ResponseDataInnerTest Class Doc Comment
 *
 * @category    Class
 * @description ListDocuments200ResponseDataInner
 * @package     Intifact\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ListDocuments200ResponseDataInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListDocuments200ResponseDataInner"
     */
    public function testListDocuments200ResponseDataInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "env"
     */
    public function testPropertyEnv()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_doc"
     */
    public function testPropertyTipoDoc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "serie"
     */
    public function testPropertySerie()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "correlativo"
     */
    public function testPropertyCorrelativo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fecha_emision"
     */
    public function testPropertyFechaEmision()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_moneda"
     */
    public function testPropertyTipoMoneda()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cliente_num_doc"
     */
    public function testPropertyClienteNumDoc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cliente_razon_social"
     */
    public function testPropertyClienteRazonSocial()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "monto_imp_venta"
     */
    public function testPropertyMontoImpVenta()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "monto_igv"
     */
    public function testPropertyMontoIgv()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "estado_sunat"
     */
    public function testPropertyEstadoSunat()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "codigo_respuesta"
     */
    public function testPropertyCodigoRespuesta()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "descripcion_respuesta"
     */
    public function testPropertyDescripcionRespuesta()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hash_cdr"
     */
    public function testPropertyHashCdr()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
