<?php
/**
 * BranchesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API de Facturación Electrónica SUNAT
 *
 * API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Intifact\Sdk\Test\Api;

use \Intifact\Sdk\Configuration;
use \Intifact\Sdk\ApiException;
use \Intifact\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BranchesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BranchesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV1CompaniesIdBranchesBranchIdDelete
     *
     * Desactivar establecimiento (soft-delete).
     *
     */
    public function testApiV1CompaniesIdBranchesBranchIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CompaniesIdBranchesBranchIdPut
     *
     * Actualizar establecimiento.
     *
     */
    public function testApiV1CompaniesIdBranchesBranchIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CompaniesIdBranchesGet
     *
     * Listar establecimientos (sucursales) de una empresa.
     *
     */
    public function testApiV1CompaniesIdBranchesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CompaniesIdBranchesPost
     *
     * Crear establecimiento (sucursal).
     *
     */
    public function testApiV1CompaniesIdBranchesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
