<?php
/**
 * DespatchApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API de Facturación Electrónica SUNAT
 *
 * API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Intifact\Sdk\Test\Api;

use \Intifact\Sdk\Configuration;
use \Intifact\Sdk\ApiException;
use \Intifact\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DespatchApiTest Class Doc Comment
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DespatchApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV1DespatchIdCdrGet
     *
     * Descargar CDR (constancia de SUNAT).
     *
     */
    public function testApiV1DespatchIdCdrGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1DespatchIdPdfGet
     *
     * Obtener PDF de la guía (A4 oficina, ticket 80mm o 58mm POS).
     *
     */
    public function testApiV1DespatchIdPdfGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1DespatchIdXmlGet
     *
     * Descargar XML firmado de la guía.
     *
     */
    public function testApiV1DespatchIdXmlGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1DespatchSendMultiPost
     *
     * Enviar múltiples guías de remisión por destino.
     *
     */
    public function testApiV1DespatchSendMultiPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1DespatchSendPost
     *
     * Enviar guía de remisión (09) via API GRE REST.
     *
     */
    public function testApiV1DespatchSendPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1DespatchTransportistaSendPost
     *
     * Enviar guía de remisión TRANSPORTISTA (31) via API GRE REST.
     *
     */
    public function testApiV1DespatchTransportistaSendPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
