<?php
/**
 * InvoiceApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API de Facturación Electrónica SUNAT
 *
 * API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Intifact\Sdk\Test\Api;

use \Intifact\Sdk\Configuration;
use \Intifact\Sdk\ApiException;
use \Intifact\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InvoiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvoiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for computeInvoice
     *
     * Calcular importes (IGV, descuentos, totales) sin emitir.
     *
     */
    public function testComputeInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getInvoiceCdr
     *
     * Descargar CDR (constancia de SUNAT).
     *
     */
    public function testGetInvoiceCdr()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getInvoicePdf
     *
     * Obtener PDF (A4 oficina, ticket 80mm o ticket 58mm POS).
     *
     */
    public function testGetInvoicePdf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getInvoiceXml
     *
     * Descargar XML firmado.
     *
     */
    public function testGetInvoiceXml()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendInvoice
     *
     * Enviar factura (01) o boleta (03) a SUNAT.
     *
     */
    public function testSendInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
