<?php
/**
 * PublicApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API de Facturación Electrónica SUNAT
 *
 * API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Intifact\Sdk\Test\Api;

use \Intifact\Sdk\Configuration;
use \Intifact\Sdk\ApiException;
use \Intifact\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PublicApiTest Class Doc Comment
 *
 * @category Class
 * @package  Intifact\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PublicApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV1PublicConsultarRucTipoDocSerieNumeroGet
     *
     * Consultar un comprobante (público, sin auth).
     *
     */
    public function testApiV1PublicConsultarRucTipoDocSerieNumeroGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PublicConsultarRucTipoDocSerieNumeroPdfGet
     *
     * Descargar PDF del comprobante (público).
     *
     */
    public function testApiV1PublicConsultarRucTipoDocSerieNumeroPdfGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PublicConsultarRucTipoDocSerieNumeroXmlGet
     *
     * Descargar XML firmado (público).
     *
     */
    public function testApiV1PublicConsultarRucTipoDocSerieNumeroXmlGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
